In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/KeithGalli/Olympics-Dataset/master/athletes/bios.csv')
df.shape

(145500, 16)

In [3]:
df.head()

,Roles,Sex,Full name,Used name,Born,Died,NOC,athlete_id,Measurements,Affiliations,Nick/petnames,Title(s),Other names,Nationality,Original name,Name order
0,Competed in Olympic Games,Male,"François Joseph Marie Antoine ""Jean-François""•...",Jean-François•Blanchy,"12 December 1886 in Bordeaux, Gironde (FRA)","2 October 1960 in Saint-Jean-de-Luz, Pyrénées-...",France,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Competed in Olympic Games,Male,Arnaud Benjamin•Boetsch,Arnaud•Boetsch,"1 April 1969 in Meulan, Yvelines (FRA)",NaN,France,2,183 cm / 76 kg,"Racing Club de France, Paris (FRA)",NaN,NaN,NaN,NaN,NaN,NaN
2,Competed in Olympic Games • Administrator,Male,Jean Laurent Robert•Borotra,Jean•Borotra,"13 August 1898 in Biarritz, Pyrénées-Atlantiqu...","17 July 1994 in Arbonne, Pyrénées-Atlantiques ...",France,3,183 cm / 76 kg,"TCP, Paris (FRA)",Le Basque Bondissant (The Bounding Basque),NaN,NaN,NaN,NaN,NaN
3,Competed in Olympic Games,Male,Jacques Marie Stanislas Jean•Brugnon,Jacques•Brugnon,"11 May 1895 in Paris VIIIe, Paris (FRA)","20 March 1978 in Monaco, Monaco (MON)",France,4,168 cm / 64 kg,"Sporting club de Paris, Paris (FRA)",Toto,NaN,NaN,NaN,NaN,NaN
4,Competed in Olympic Games,Male,Henry Albert•Canet,Albert•Canet,"17 April 1878 in Wandsworth, England (GBR)","25 July 1930 in Paris VIIe, Paris (FRA)",France,5,NaN,"TCP, Paris (FRA)",NaN,NaN,NaN,NaN,NaN,NaN

1) Cleaning birth date and death date columns

In [4]:
df['birth_date'] = df.Born.str.split(' in').str[0]

In [5]:
df['birth_date'] = pd.to_datetime(df['Born'], format='%d %B %Y', errors='coerce')

In [6]:
# df.drop(columns=['Born'], inplace=True)

In [7]:
df['death_date'] = df.Died.str.split(' in').str[0]

In [8]:
df['death_date'] = pd.to_datetime(df['Died'], format='%d %B %Y', errors='coerce')

In [9]:
# df.drop(columns=['Died'], inplace=True)

2) Cleaning Height and Weights from Measurements column

In [10]:
df['Height'] = df.Measurements.str.split(' cm /').str[0]

In [11]:
df.Height = pd.to_numeric(df.Height, errors='coerce').astype('Int64')

In [12]:
df.Height.isna().sum()

np.int64(42472)

In [13]:
df['Weight'] = df.Measurements.str.split(' cm /').str[1].str.split(' kg').str[0]
df.Weight = pd.to_numeric(df.Weight, errors='coerce').astype('Int64')

In [14]:
df.Weight.isna().sum()

np.int64(43430)

In [15]:
# df.drop(columns=['Measurements'], inplace=True)

In [24]:
df.tail()

,Roles,Sex,Full name,Used name,Born,Died,NOC,athlete_id,Measurements,Affiliations,...,Nationality,Original name,Name order,birth_date,death_date,Height,Weight,city,region,country
145495,Competed in Olympic Games,Female,Polina Luchnikova,Polina Luchnikova,"30 January 2002 in Serov, Sverdlovsk (RUS)",NaN,ROC,149222,167 cm / 61 kg,"Agidel, Ufa (RUS)",...,NaN,NaN,NaN,NaT,NaT,167,61,Serov,Sverdlovsk,RUS
145496,Competed in Olympic Games,Female,Valeriya Sergeyevna Merkusheva,Valeriya Merkusheva,"20 September 1999 in Moskva (Moscow), Moskva (...",NaN,ROC,149223,168 cm / 65 kg,"SKIF Nizhny Novgorod, Nizhny Novgorod (RUS)",...,NaN,Валерия Сергеевна•Меркушева,NaN,NaT,NaT,168,65,Moskva,Moskva,RUS
145497,Competed in Olympic Games,Female,Yuliya Smirnova,Yuliya Smirnova,"8 May 1998 in Kotlas, Arkhangelsk (RUS)",NaN,ROC,149224,163 cm / 55 kg,"Agidel, Ufa (RUS)",...,NaN,Юлия•Смирнова,NaN,NaT,NaT,163,55,Kotlas,Arkhangelsk,RUS
145498,Competed in Olympic Games,Male,André Foussard,André Foussard,"19 May 1899 in Niort, Deux-Sèvres (FRA)","18 March 1986 in Niort, Deux-Sèvres (FRA)",France,149225,166 cm,"Beauvoisine FC, Rouen (FRA)",...,NaN,NaN,NaN,NaT,NaT,<NA>,<NA>,Niort,Deux,FRA
145499,Non-starter • Administrator,Male,"William Berge ""Bill"" Phillips",Bill Phillips,"15 July 1913 in Dulwich Hill, New South Wales ...","20 October 2003 in Sydney, New South Wales (AUS)",Australia,149814,NaN,NaN,...,NaN,NaN,NaN,NaT,NaT,<NA>,<NA>,Dulwich,New,AUS

3) get rid of bullet points in columns `Full name` and `Used name`

In [17]:
df['Full name'] = df['Full name'].str.replace('•', ' ')

In [18]:
df['Used name'] = df['Used name'].str.replace('•', ' ')

In [19]:
# This is other way to do it 
# df[['height', 'weight']] = df.Measurements.str.split(' /', expand=True).head()

In [25]:
city_pattern = r'in ([\w]+)' 
region_pattern = r', ([\w ]+)' 
country_pattern = r'\((\w{3})\)$'

df['city'] = df.Born.str.extract(city_pattern, expand=False)
df['region'] = df.Born.str.extract(region_pattern, expand=False)
df['country'] = df.Born.str.extract(country_pattern, expand=False)

In [26]:
df

,Roles,Sex,Full name,Used name,Born,Died,NOC,athlete_id,Measurements,Affiliations,...,Nationality,Original name,Name order,birth_date,death_date,Height,Weight,city,region,country
0,Competed in Olympic Games,Male,"François Joseph Marie Antoine ""Jean-François"" ...",Jean-François Blanchy,"12 December 1886 in Bordeaux, Gironde (FRA)","2 October 1960 in Saint-Jean-de-Luz, Pyrénées-...",France,1,NaN,NaN,...,NaN,NaN,NaN,NaT,NaT,<NA>,<NA>,Bordeaux,Gironde,FRA
1,Competed in Olympic Games,Male,Arnaud Benjamin Boetsch,Arnaud Boetsch,"1 April 1969 in Meulan, Yvelines (FRA)",NaN,France,2,183 cm / 76 kg,"Racing Club de France, Paris (FRA)",...,NaN,NaN,NaN,NaT,NaT,183,76,Meulan,Yvelines,FRA
2,Competed in Olympic Games • Administrator,Male,Jean Laurent Robert Borotra,Jean Borotra,"13 August 1898 in Biarritz, Pyrénées-Atlantiqu...","17 July 1994 in Arbonne, Pyrénées-Atlantiques ...",France,3,183 cm / 76 kg,"TCP, Paris (FRA)",...,NaN,NaN,NaN,NaT,NaT,183,76,Biarritz,Pyrénées,FRA
3,Competed in Olympic Games,Male,Jacques Marie Stanislas Jean Brugnon,Jacques Brugnon,"11 May 1895 in Paris VIIIe, Paris (FRA)","20 March 1978 in Monaco, Monaco (MON)",France,4,168 cm / 64 kg,"Sporting club de Paris, Paris (FRA)",...,NaN,NaN,NaN,NaT,NaT,168,64,Paris,Paris,FRA
4,Competed in Olympic Games,Male,Henry Albert Canet,Albert Canet,"17 April 1878 in Wandsworth, England (GBR)","25 July 1930 in Paris VIIe, Paris (FRA)",France,5,NaN,"TCP, Paris (FRA)",...,NaN,NaN,NaN,NaT,NaT,<NA>,<NA>,Wandsworth,England,GBR
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145495,Competed in Olympic Games,Female,Polina Luchnikova,Polina Luchnikova,"30 January 2002 in Serov, Sverdlovsk (RUS)",NaN,ROC,149222,167 cm / 61 kg,"Agidel, Ufa (RUS)",...,NaN,NaN,NaN,NaT,NaT,167,61,Serov,Sverdlovsk,RUS
145496,Competed in Olympic Games,Female,Valeriya Sergeyevna Merkusheva,Valeriya Merkusheva,"20 September 1999 in Moskva (Moscow), Moskva (...",NaN,ROC,149223,168 cm / 65 kg,"SKIF Nizhny Novgorod, Nizhny Novgorod (RUS)",...,NaN,Валерия Сергеевна•Меркушева,NaN,NaT,NaT,168,65,Moskva,Moskva,RUS
145497,Competed in Olympic Games,Female,Yuliya Smirnova,Yuliya Smirnova,"8 May 1998 in Kotlas, Arkhangelsk (RUS)",NaN,ROC,149224,163 cm / 55 kg,"Agidel, Ufa (RUS)",...,NaN,Юлия•Смирнова,NaN,NaT,NaT,163,55,Kotlas,Arkhangelsk,RUS
145498,Competed in Olympic Games,Male,André Foussard,André Foussard,"19 May 1899 in Niort, Deux-Sèvres (FRA)","18 March 1986 in Niort, Deux-Sèvres (FRA)",France,149225,166 cm,"Beauvoisine FC, Rouen (FRA)",...,NaN,NaN,NaN,NaT,NaT,<NA>,<NA>,Niort,Deux,FRA
145499,Non-starter • Administrator,Male,"William Berge ""Bill"" Phillips",Bill Phillips,"15 July 1913 in Dulwich Hill, New South Wales ...","20 October 2003 in Sydney, New South Wales (AUS)",Australia,149814,NaN,NaN,...,NaN,NaN,NaN,NaT,NaT,<NA>,<NA>,Dulwich,New South Wales,AUS